# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-14 18:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0006_teacher_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseorg',
            name='tag',
            field=models.CharField(default='\u5c0f\u7199\u52aa\u529b', max_length=10, verbose_name='\u673a\u6784\u6807\u7b7e'),
        ),
    ]
